Repository SCE-Development/Quasar, pull requests merged in 2021-12, with the labels that each got.

#1 Add config folder
  .gitignore
  config/config.example.json
Labels: good first issue, rayquaza

#3 Printer SQS Read that lives on the VM
  .gitignore
  README.md
  package-lock.json
  printer/PrintHandler.js
  test.js
Labels: printing

#8 Add ESLint to Quasar
  .eslintrc.json
  .github/workflows/node.js.yml
  README.md
  package-lock.json
  package.json
  printer/PrintHandler.js
  test.js
Labels: enhancement

#2 Added code for reading SQS for LED Sign
  config/config.example.json
  ledsign/LEDSignHandler.js
  package-lock.json
  package.json
Labels: bug, documentation, enhancement, good first issue, help wanted, rayquaza, led sign
