Repository SCE-Development/Quasar, pull requests merged in 2022-06, with the labels that each got.

#39 fix sqs message parse
  util/SqsMessageHandler.js
Labels: bug, rayquaza

#40 add cadvisor to docker compose
  docker-compose.yml
Labels: enhancement, monitoring/alerting

#41 Prometheus for cadvisor metrics
  docker-compose.yml
  prometheus/prometheus.yml
Labels: enhancement, monitoring/alerting

#47 bump LED-Sign node version to 14
  ledsign/Dockerfile
Labels: enhancement, monitoring/alerting

#44 add bash script for ssh tunneling
  config/config.example.json
  tunnel/tun.sh
Labels: enhancement, rayquaza, health check

#45 Host flask server to show whether quasar is up (using ssh tunnel)
  tunnel/app.py
  tunnel/tun.sh
Labels: health check

#50 Dockerize health check tunnel
  config/config.example.json
  docker-compose.yml
  tunnel/Dockerfile
  tunnel/app.py
  tunnel/tun.sh
Labels: health check

#52 added comments for tunnel/tun.sh
  tunnel/tun.sh
Labels: health check

#42 Grafana to get prometheus metrics
  docker-compose.yml
  ledsign/LEDSignHandler.js
  monitoring/grafana/grafana.ini
  monitoring/grafana/provisioning/dashboards/all.yml
  monitoring/grafana/provisioning/dashboards/dashboard.json
  monitoring/grafana/provisioning/datasources/all.yml
  monitoring/prometheus/prometheus.yml
  package-lock.json
  package.json
  prometheus/prometheus.yml
Labels: enhancement, monitoring/alerting

#54 Use jq to parse config.json values
  README.md
  config/config.example.json
  printer/what.sh
Labels: enhancement, printing

#43 Prometheus and Grafana now sit behind Nginx
  docker-compose.yml
  nginx.conf
Labels: enhancement, monitoring/alerting

#58 Create class for HP Laserjet SNMP Queries
  printer/snmp.js
  printer/util.js
Labels: rayquaza, printing, monitoring/alerting

#61 Add Logging to Quasar
  util/logger.js
Labels: enhancement, monitoring/alerting

#56 Default to port 14000 for health check server
  healthcheck/app.py
Labels: enhancement, health check
