Repository SCE-Development/Quasar, pull requests merged in 2022-02, with the labels that each got.

#11 Store downloaded files from s3 in /tmp
  printer/PrintHandler.js
Labels: rayquaza, printing

#12 Delete print request from SQS on successful print
  printer/PrintHandler.js
Labels: bug, printing

#16 Change AWS region for LED queue
  ledsign/LEDSignHandler.js
Labels: enhancement, rayquaza, led sign

#15 Document printing setup steps
  README.md
  printer/Dockerfile
  printer/PrintHandler.js
  printer/what.sh
  what.sh
Labels: documentation, enhancement, rayquaza, printing
