Repository SCE-Development/Quasar, pull requests merged in 2022-08, with the labels that each got.

#70 Updated Config File
  .gitignore
  config/config.example.json
  ledsign/LEDSignHandler.js
  printer/PrintHandler.js
  printer/what.sh
  util/.DS_Store
Labels: enhancement

#64 Add scraper to docker yml
  docker-compose.yml
  printer/scraper/Dockerfile
  printer/scraper/main.js
  printer/scraper/start_scraper.sh
Labels: enhancement, rayquaza, monitoring/alerting

#75 Add live reloading for containers
  docker-compose.dev.yml
  ledsign/Dockerfile.dev
  printer/Dockerfile.dev
  printer/run_dev_container.sh
Labels: documentation

#83 Change container not running to 60 seconds
  monitoring/prometheus/alert_rules.yml
Labels: monitoring/alerting

#80 created function to support printing from Discord
  printer/PrintHandler.js
Labels: enhancement, printing

#88 Fix Health Check Tunnel
  docker-compose.yml
  healthcheck/Dockerfile
  healthcheck/tun.sh
Labels: health check

#89 Add health check IP in config.example.json
  config/config.example.json
  ledsign/LEDSignHandler.js
  printer/scraper/start_scraper.sh
Labels: health check
