Repository SCE-Development/Quasar, pull requests merged in 2022-07, with the labels that each got.

#66 Create Scraper for Printer Metrics over SNMP
  docker-compose.yml
  printer/scraperPrinter/InfluxHandler.js
  printer/scraperPrinter/printerScraper.js
  printer/snmp.js
Labels: enhancement, rayquaza, printing, monitoring/alerting

#71 Create Dev Tool Function to write to SQS
  .gitignore
  package.json
  printer/scraperPrinter/InfluxHandler.js
  printer/scraperPrinter/printerScraper.js
  tools/blank.pdf
  tools/writeToSQS.js
  util/.DS_Store
  util/logger.js
Labels: enhancement, printing

#73 Add Prometheus alerts for container not running
  docker-compose.yml
  monitoring/prometheus/alert_rules.yml
  monitoring/prometheus/prometheus.yml
Labels: enhancement, monitoring/alerting
