Repository SCE-Development/Quasar, pull requests merged in 2022-03, with the labels that each got.

#23 Add support for copies from Core-v4
  printer/PrintHandler.js
Labels: enhancement, rayquaza, printing

#26 Abstract SQS read to a function
  ledsign/LEDSignHandler.js
  printer/PrintHandler.js
  util/SqsMessageHandler.js
Labels: enhancement, rayquaza, printing, led sign

#25 Add support for page range from Core-v4
  printer/PrintHandler.js
Labels: enhancement, printing
